/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronteira;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tiago
 */
public class tblGastos extends javax.swing.JPanel {

    /**
     * Creates new form tblGastos
     */
    public tblGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlBairroCRUD = new javax.swing.JPanel();
        lblGasto = new javax.swing.JLabel();
        btnAdicionarGasto = new javax.swing.JButton();
        btnSelecionarGasto = new javax.swing.JButton();
        btnRemoverGasto = new javax.swing.JButton();
        lblGastos = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        txtGasto = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnEfetuar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTableGasto = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(800, 600));

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        lblGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGasto.setText("Gasto:");

        btnAdicionarGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarGasto.setText("Adicionar");
        btnAdicionarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGastoActionPerformed(evt);
            }
        });

        btnSelecionarGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelecionarGasto.setText("Selecionar");
        btnSelecionarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarGastoActionPerformed(evt);
            }
        });

        btnRemoverGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverGasto.setText("Remover");
        btnRemoverGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverGastoActionPerformed(evt);
            }
        });

        lblGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGastos.setText("Gastos:");

        lbValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbValor.setText("Valor:");

        txtGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGastoActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnEfetuar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEfetuar.setText("Efetuar");

        tblTableGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gasto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTableGasto);
        if (tblTableGasto.getColumnModel().getColumnCount() > 0) {
            tblTableGasto.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        javax.swing.GroupLayout pnlBairroCRUDLayout = new javax.swing.GroupLayout(pnlBairroCRUD);
        pnlBairroCRUD.setLayout(pnlBairroCRUDLayout);
        pnlBairroCRUDLayout.setHorizontalGroup(
            pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGastos)
                    .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                        .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                                        .addComponent(lblGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(396, 396, 396))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBairroCRUDLayout.createSequentialGroup()
                                        .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValor)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoverGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionarGasto)
                            .addComponent(btnAdicionarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEfetuar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlBairroCRUDLayout.setVerticalGroup(
            pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGastos)
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(btnAdicionarGasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionarGasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverGasto)
                        .addGap(21, 21, 21))
                    .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGasto)
                    .addComponent(lbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEfetuar))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBairroCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBairroCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGastoActionPerformed
        //Valores das caixas de texto
        String gasto, valor;

        //pegando valores
        gasto = txtGasto.getText();
        valor = txtValor.getText();

        //jogando na tabela
        if(gasto.isEmpty()==false && valor.isEmpty()==false){
            DefaultTableModel model = (DefaultTableModel) tblTableGasto.getModel();
            model.addRow(new Object[]{gasto, valor});
            txtGasto.setText("");
            txtValor.setText("");
        }
    }//GEN-LAST:event_btnAdicionarGastoActionPerformed

    private void btnSelecionarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarGastoActionPerformed
        // Alterar complemento da tabela
        DefaultTableModel model = (DefaultTableModel) tblTableGasto.getModel();
        int row = tblTableGasto.getSelectedRow();
        if(row != -1){
            //Variáveis para armazenar valores atuais das listas
            String gasto, valor;

            //pegando valores
            gasto = tblTableGasto.getValueAt(tblTableGasto.getSelectedRow(),0).toString();
            valor = tblTableGasto.getValueAt(tblTableGasto.getSelectedRow(),1).toString();

            txtGasto.setText(gasto);
            txtValor.setText(valor);
        }
    }//GEN-LAST:event_btnSelecionarGastoActionPerformed

    private void btnRemoverGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverGastoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblTableGasto.getModel();
        int row = tblTableGasto.getSelectedRow();
        if(row != -1){
            //removendo
            model.removeRow(row);
        }
    }//GEN-LAST:event_btnRemoverGastoActionPerformed

    private void txtGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGastoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarGasto;
    private javax.swing.JButton btnEfetuar;
    private javax.swing.JButton btnRemoverGasto;
    private javax.swing.JButton btnSelecionarGasto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlBairroCRUD;
    private javax.swing.JTable tblTableGasto;
    private javax.swing.JTextField txtGasto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
