/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronteira;

/**
 *
 * @author Tiago
 */
public class tblRelatorio extends javax.swing.JPanel {

    /**
     * Creates new form tblRelatorio
     */
    public tblRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblRelatorio = new javax.swing.JLabel();
        pnlRel = new javax.swing.JPanel();
        lblAcai = new javax.swing.JLabel();
        lblVitamina = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblLucro = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        txtGasto = new javax.swing.JTextField();
        txtLucro = new javax.swing.JTextField();
        txtAcaiUnidade = new javax.swing.JTextField();
        txtVitaminaUnidade = new javax.swing.JTextField();
        txtTotalUnidade = new javax.swing.JTextField();
        txtTotalValor = new javax.swing.JTextField();
        txtVitaminaValor = new javax.swing.JTextField();
        txtAcaiValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedidos = new javax.swing.JTextArea();
        btnInicio = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        lblRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRelatorio.setText("Relatório:");

        pnlRel.setBackground(new java.awt.Color(200, 200, 200));

        lblAcai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcai.setText("Açaís vendidos:          ............................................................................");

        lblVitamina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVitamina.setText("Vitaminas vendidas:    ............................................................................");

        lblVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVendas.setText("Total de vendas:         ............................................................................");

        lblGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGastos.setText("Gastos:                       ...............................");

        lblLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLucro.setText("Lucro total:       ...............................");

        lblPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPedidos.setText("Pedidos:                     ______________________________________________________________________");

        txtGasto.setEditable(false);
        txtGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGasto.setText("R$");

        txtLucro.setEditable(false);
        txtLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLucro.setText("R$");

        txtAcaiUnidade.setEditable(false);
        txtAcaiUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVitaminaUnidade.setEditable(false);
        txtVitaminaUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTotalUnidade.setEditable(false);
        txtTotalUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTotalValor.setEditable(false);
        txtTotalValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalValor.setText("R$");

        txtVitaminaValor.setEditable(false);
        txtVitaminaValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVitaminaValor.setText("R$");

        txtAcaiValor.setEditable(false);
        txtAcaiValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAcaiValor.setText("R$");

        txtPedidos.setEditable(false);
        txtPedidos.setColumns(20);
        txtPedidos.setRows(5);
        jScrollPane1.setViewportView(txtPedidos);

        javax.swing.GroupLayout pnlRelLayout = new javax.swing.GroupLayout(pnlRel);
        pnlRel.setLayout(pnlRelLayout);
        pnlRelLayout.setHorizontalGroup(
            pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRelLayout.createSequentialGroup()
                        .addComponent(lblGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                            .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlRelLayout.createSequentialGroup()
                                    .addComponent(lblVendas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTotalUnidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                                    .addComponent(lblVitamina)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtVitaminaUnidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                                    .addComponent(lblAcai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAcaiUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTotalValor)
                                .addComponent(txtVitaminaValor)
                                .addComponent(txtAcaiValor)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRelLayout.setVerticalGroup(
            pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcai)
                    .addComponent(txtAcaiUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcaiValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVitamina)
                    .addComponent(txtVitaminaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVitaminaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendas)
                    .addComponent(txtTotalUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGastos)
                    .addComponent(lblLucro)
                    .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInicio.setText("Início");

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicio)
                    .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRelatorio)
                        .addComponent(pnlRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcai;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lblVitamina;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlRel;
    private javax.swing.JTextField txtAcaiUnidade;
    private javax.swing.JTextField txtAcaiValor;
    private javax.swing.JTextField txtGasto;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextArea txtPedidos;
    private javax.swing.JTextField txtTotalUnidade;
    private javax.swing.JTextField txtTotalValor;
    private javax.swing.JTextField txtVitaminaUnidade;
    private javax.swing.JTextField txtVitaminaValor;
    // End of variables declaration//GEN-END:variables
}
