/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronteira;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tiago
 */
public class tblVitaminas extends javax.swing.JPanel {

    /**
     * Creates new form tblVitaminas
     */
    public tblVitaminas() {
        initComponents();
        
        setTableVitamina();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlVitaminas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitaminas = new javax.swing.JTable();
        btnVitRemover = new javax.swing.JButton();
        btnVitSelecionar = new javax.swing.JButton();
        btnVitAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtVitNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVitValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVitSabor = new javax.swing.JTextField();
        btnVitAlterar = new javax.swing.JButton();

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Vitaminas:");

        tblVitaminas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sabor", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVitaminas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblVitaminas);
        if (tblVitaminas.getColumnModel().getColumnCount() > 0) {
            tblVitaminas.getColumnModel().getColumn(0).setResizable(false);
            tblVitaminas.getColumnModel().getColumn(1).setResizable(false);
            tblVitaminas.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblVitaminas.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVitRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitRemover.setText("Remover");
        btnVitRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitRemoverActionPerformed(evt);
            }
        });

        btnVitSelecionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitSelecionar.setText("Selecionar");
        btnVitSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitSelecionarActionPerformed(evt);
            }
        });

        btnVitAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitAdicionar.setText("Adicionar");
        btnVitAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        txtVitNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor:");

        txtVitValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sabor:");

        txtVitSabor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnVitAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitAlterar.setText("Alterar");

        javax.swing.GroupLayout pnlVitaminasLayout = new javax.swing.GroupLayout(pnlVitaminas);
        pnlVitaminas.setLayout(pnlVitaminasLayout);
        pnlVitaminasLayout.setHorizontalGroup(
            pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVitaminasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVitaminasLayout.createSequentialGroup()
                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlVitaminasLayout.createSequentialGroup()
                                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                                        .addComponent(txtVitNome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtVitSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3)
                                        .addGap(71, 71, 71))
                                    .addComponent(txtVitValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVitSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVitAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVitRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVitAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlVitaminasLayout.setVerticalGroup(
            pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVitaminasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addComponent(btnVitAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVitSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVitRemover))
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlVitaminasLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVitNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlVitaminasLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVitSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVitValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVitAlterar))))
                .addGap(240, 240, 240))
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVitaminas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVitaminas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitAdicionarActionPerformed
        //Valores das caixas de texto
        String nome, sabor, valor;
        
        //pegando valores
        nome = txtVitNome.getText();
        sabor = txtVitSabor.getText();
        valor = txtVitValor.getText();
        
        //jogando na tabela
        if(nome.isEmpty()==false && sabor.isEmpty() == false && valor.isEmpty()==false){
            DefaultTableModel model = (DefaultTableModel) tblVitaminas.getModel();
            model.addRow(new Object[]{nome, sabor, valor});
            txtVitNome.setText("");
            txtVitSabor.setText("");
            txtVitValor.setText("");
        }
    }//GEN-LAST:event_btnVitAdicionarActionPerformed

    private void btnVitRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitRemoverActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblVitaminas.getModel();
        int row = tblVitaminas.getSelectedRow();
        if(row != -1){
             //removendo
            model.removeRow(row);
        }
    }//GEN-LAST:event_btnVitRemoverActionPerformed

    private void btnVitSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitSelecionarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblVitaminas.getModel();
        int row = tblVitaminas.getSelectedRow();
        if(row != -1){
             //Variáveis para armazenar valores atuais das listas
            String nome, sabor, valor;

            //pegando valores
            nome = tblVitaminas.getValueAt(tblVitaminas.getSelectedRow(),0).toString();
            sabor = tblVitaminas.getValueAt(tblVitaminas.getSelectedRow(),1).toString();
            valor = tblVitaminas.getValueAt(tblVitaminas.getSelectedRow(),2).toString();

            txtVitNome.setText(nome);
            txtVitSabor.setText(sabor);
            txtVitValor.setText(valor);
        }
    }//GEN-LAST:event_btnVitSelecionarActionPerformed

    private void setTableVitamina(){
        //listar todos os produtos adicionado
        
        String nome, sabor, valor;
        
        //Tabela vazia
        DefaultTableModel model = (DefaultTableModel) tblVitaminas.getModel();
        
        //valores fictícios, os originais devem ser puxados do BD
        nome = "Vit.1"; sabor="Açaí + Leite + Leite em pó + Banana"; valor = "8.00";
        model.addRow(new Object[]{nome, sabor, valor});
        
        nome = "Vit.2"; sabor="Açaí + Leite + Leite em pó + Morango"; valor = "10.00";
        model.addRow(new Object[]{nome, sabor, valor});
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVitAdicionar;
    private javax.swing.JButton btnVitAlterar;
    private javax.swing.JButton btnVitRemover;
    private javax.swing.JButton btnVitSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlVitaminas;
    private javax.swing.JTable tblVitaminas;
    private javax.swing.JTextField txtVitNome;
    private javax.swing.JTextField txtVitSabor;
    private javax.swing.JTextField txtVitValor;
    // End of variables declaration//GEN-END:variables
}
