package Fronteira;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class InicioMDI extends javax.swing.JFrame {

    public InicioMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnlBack = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon ("src\\Imagens\\back3.jpg");
                Image i = im.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        mnBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnMenuPedidos = new javax.swing.JMenu();
        mniNovo = new javax.swing.JMenuItem();
        mniPedidos = new javax.swing.JMenuItem();
        mnMenuCadastro = new javax.swing.JMenu();
        mniTamanhos = new javax.swing.JMenuItem();
        mniComplementos = new javax.swing.JMenuItem();
        mniVitaminas = new javax.swing.JMenuItem();
        mniBairros = new javax.swing.JMenuItem();
        mniGastos = new javax.swing.JMenuItem();
        mniRelatorio = new javax.swing.JMenuItem();
        mnMenuCozinha = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SKINA DO AÇAÍ");
        setResizable(false);

        pnlBack.setBackground(new java.awt.Color(82, 52, 117));

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jMenu3.setText("Inicio");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        mnBar.add(jMenu3);

        mnMenuPedidos.setText("Pedidos");

        mniNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mniNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-novo-por-cópia-26.png"))); // NOI18N
        mniNovo.setText("Novo Pedido");
        mniNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoActionPerformed(evt);
            }
        });
        mnMenuPedidos.add(mniNovo);

        mniPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mniPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-table-and-graph-24.png"))); // NOI18N
        mniPedidos.setText("Pedidos em andamento");
        mniPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPedidosActionPerformed(evt);
            }
        });
        mnMenuPedidos.add(mniPedidos);

        mnBar.add(mnMenuPedidos);

        mnMenuCadastro.setText("Cadastro");

        mniTamanhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-copa-do-solo-24.png"))); // NOI18N
        mniTamanhos.setText("Tamanho Açaí");
        mniTamanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTamanhosActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniTamanhos);

        mniComplementos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-morango-24.png"))); // NOI18N
        mniComplementos.setText("Complementos");
        mniComplementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniComplementosActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniComplementos);

        mniVitaminas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-milk-shake-24.png"))); // NOI18N
        mniVitaminas.setText("Vitaminas");
        mniVitaminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVitaminasActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniVitaminas);

        mniBairros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-vista-da-rua-26.png"))); // NOI18N
        mniBairros.setText("Bairros");
        mniBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBairrosActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniBairros);

        mniGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pilha-de-dinheiro-26.png"))); // NOI18N
        mniGastos.setText("Gastos");
        mniGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGastosActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniGastos);

        mniRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-saco-de-dinheiro-24.png"))); // NOI18N
        mniRelatorio.setText("Relatório");
        mniRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRelatorioActionPerformed(evt);
            }
        });
        mnMenuCadastro.add(mniRelatorio);

        mnBar.add(mnMenuCadastro);

        mnMenuCozinha.setText("Cozinha");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-sala-de-jantar-24.png"))); // NOI18N
        jMenuItem1.setText("Pedidos na cozinha");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnMenuCozinha.add(jMenuItem1);

        mnBar.add(mnMenuCozinha);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoActionPerformed
        TlNovoPedido tbl_novo = new TlNovoPedido(this);
        setContentPane(tbl_novo);
        revalidate();
    }//GEN-LAST:event_mniNovoActionPerformed

    private void mniPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPedidosActionPerformed
        TblPedidosEmAndamento tbl_pedidos = new TblPedidosEmAndamento();
        setContentPane(tbl_pedidos);
        revalidate();
    }//GEN-LAST:event_mniPedidosActionPerformed

    private void mniComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniComplementosActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Complemento");
        lg.setVisible(true);

    }//GEN-LAST:event_mniComplementosActionPerformed

    private void mniBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBairrosActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Bairro");
        lg.setVisible(true);

    }//GEN-LAST:event_mniBairrosActionPerformed

    private void mniGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGastosActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Gasto");
        lg.setVisible(true);
    }//GEN-LAST:event_mniGastosActionPerformed

    private void mniRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRelatorioActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Relatorio");
        lg.setVisible(true);
    }//GEN-LAST:event_mniRelatorioActionPerformed

    private void mniVitaminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVitaminasActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Vitamina");
        lg.setVisible(true);
    }//GEN-LAST:event_mniVitaminasActionPerformed

    private void mniTamanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTamanhosActionPerformed

        this.dispose();
        tblLogin lg = new tblLogin("Acai");
        lg.setVisible(true);

    }//GEN-LAST:event_mniTamanhosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        tblCozinha cz = new tblCozinha();
        cz.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed

        setContentPane(pnlBack);
        revalidate();
    }//GEN-LAST:event_jMenu3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenu mnMenuCadastro;
    private javax.swing.JMenu mnMenuCozinha;
    private javax.swing.JMenu mnMenuPedidos;
    private javax.swing.JMenuItem mniBairros;
    private javax.swing.JMenuItem mniComplementos;
    private javax.swing.JMenuItem mniGastos;
    private javax.swing.JMenuItem mniNovo;
    private javax.swing.JMenuItem mniPedidos;
    private javax.swing.JMenuItem mniRelatorio;
    private javax.swing.JMenuItem mniTamanhos;
    private javax.swing.JMenuItem mniVitaminas;
    public javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
