package Fronteira;

import Controle.ClsRelacional;
import Persistencia.PerAcai;
import Persistencia.PerGastos;
import Persistencia.PerRelacional;
import Persistencia.PerVitamina;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class tblRelatorio extends javax.swing.JPanel {

    String dataTexto;

    public tblRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon ("src\\Imagens\\back6.jpg");
                Image i = im.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        lblRelatorio = new javax.swing.JLabel();
        pnlRel = new javax.swing.JPanel();
        lblAcai = new javax.swing.JLabel();
        lblVitamina = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblLucro = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        txtGasto = new javax.swing.JTextField();
        txtLucro = new javax.swing.JTextField();
        txtAcaiUnidade = new javax.swing.JTextField();
        txtVitaminaUnidade = new javax.swing.JTextField();
        txtTotalUnidade = new javax.swing.JTextField();
        txtTotalValor = new javax.swing.JTextField();
        txtVitaminaValor = new javax.swing.JTextField();
        txtAcaiValor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        txtDATE = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(800, 600));

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        lblRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRelatorio.setText("Relatório:");

        pnlRel.setBackground(new java.awt.Color(200, 200, 200));

        lblAcai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcai.setText("Açaís vendidos:          ............................................................................");

        lblVitamina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVitamina.setText("Vitaminas vendidas:    ............................................................................");

        lblVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVendas.setText("Total de vendas:         ............................................................................");

        lblGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGastos.setText("Gastos:                       ...............................");

        lblLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLucro.setText("Lucro total:       ...............................");

        lblPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPedidos.setText("Pedidos:                     ______________________________________________________________________");

        txtGasto.setEditable(false);
        txtGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGasto.setText("R$");

        txtLucro.setEditable(false);
        txtLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLucro.setText("R$");

        txtAcaiUnidade.setEditable(false);
        txtAcaiUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVitaminaUnidade.setEditable(false);
        txtVitaminaUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTotalUnidade.setEditable(false);
        txtTotalUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTotalValor.setEditable(false);
        txtTotalValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalValor.setText("R$");

        txtVitaminaValor.setEditable(false);
        txtVitaminaValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVitaminaValor.setText("R$");

        txtAcaiValor.setEditable(false);
        txtAcaiValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAcaiValor.setText("R$");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Tamanho/Tipo Vitamina", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPedidos);

        javax.swing.GroupLayout pnlRelLayout = new javax.swing.GroupLayout(pnlRel);
        pnlRel.setLayout(pnlRelLayout);
        pnlRelLayout.setHorizontalGroup(
            pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRelLayout.createSequentialGroup()
                        .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRelLayout.createSequentialGroup()
                                .addComponent(lblGastos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLucro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                                    .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlRelLayout.createSequentialGroup()
                                            .addComponent(lblVendas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTotalUnidade))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                                            .addComponent(lblVitamina)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtVitaminaUnidade))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRelLayout.createSequentialGroup()
                                            .addComponent(lblAcai)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAcaiUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotalValor)
                                        .addComponent(txtVitaminaValor)
                                        .addComponent(txtAcaiValor)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        pnlRelLayout.setVerticalGroup(
            pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcai)
                    .addComponent(txtAcaiUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcaiValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVitamina)
                    .addComponent(txtVitaminaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVitaminaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendas)
                    .addComponent(txtTotalUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGastos)
                    .addComponent(lblLucro)
                    .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Escreva a data que deseja consultar");

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmar))
                    .addComponent(lblRelatorio)
                    .addComponent(pnlRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnConfirmar)
                    .addComponent(txtDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        Date data = null;
        double gastosT = 0, vitaminaT = 0, acaiT = 0, totalT = 0;
        int qntdV = 0, qntdA = 0;

        dataTexto = txtDATE.getText();

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

        try {
            format.setLenient(false);
            data = format.parse(dataTexto);

            //código de todos os pedidos referente a data escolhida  para preencher a tabela
            PreencherTabela();

            qntdV = PerVitamina.QuantidadeTotal(dataTexto);

            qntdA = PerAcai.QuantidadeTotal(dataTexto);

            vitaminaT = PerVitamina.ValorTotal(dataTexto);

            acaiT = PerAcai.ValorTotal(dataTexto);

            gastosT = PerGastos.GastosData(dataTexto);

            totalT = vitaminaT + acaiT;

            //código dos gastos            
            txtAcaiUnidade.setText(qntdA + "");
            txtAcaiValor.setText(acaiT + "");
            txtVitaminaUnidade.setText(qntdV + "");
            txtVitaminaValor.setText(vitaminaT + "");

            txtTotalUnidade.setText((qntdV + qntdA) + "");
            txtTotalValor.setText((acaiT + vitaminaT) + "");
            txtGasto.setText(gastosT + "");
            txtLucro.setText((totalT - gastosT) + "");

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Data inválida, use / entre os números.\nExemplo: 23/12/2020", "AVISO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    public void PreencherTabela() {

        DefaultTableModel model = (DefaultTableModel) tblPedidos.getModel();
        //vai limpar a tabela
        int t = model.getRowCount();
        for (int i = 0; i < t; i++) {
            model.removeRow(0);
        }

        PerRelacional perRelacional = new PerRelacional();
        ArrayList<ClsRelacional> relacional = PerRelacional.PedidoRelatorio(dataTexto);

        //vai preencher a tabela
        for (ClsRelacional q : relacional) {
            String linha[] = new String[3];

            if (q.getIdProduto() == 1) {
                linha[0] = "Açaí";
                linha[1] = q.getTamanhoAcai();
            } else {
                linha[0] = "Vitamina";
                linha[1] = q.getTipoVitamina();
            }

            linha[2] = q.getValorPedido();

            model.addRow(linha);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAcai;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lblVitamina;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlRel;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtAcaiUnidade;
    private javax.swing.JTextField txtAcaiValor;
    private javax.swing.JTextField txtDATE;
    private javax.swing.JTextField txtGasto;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtTotalUnidade;
    private javax.swing.JTextField txtTotalValor;
    private javax.swing.JTextField txtVitaminaUnidade;
    private javax.swing.JTextField txtVitaminaValor;
    // End of variables declaration//GEN-END:variables
}
