package Fronteira;

import Controle.ClsBairros;
import Persistencia.PerBairros;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class TlBairros extends javax.swing.JPanel {

    DefaultTableModel vTabela = new DefaultTableModel();

    public TlBairros() {
        initComponents();
        vTabela.addColumn("Cod.");
        vTabela.addColumn("Nome do bairro");
        vTabela.addColumn("Preço");
        PreencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlBairroCRUD = new javax.swing.JPanel();
        lblBairros = new javax.swing.JLabel();
        btnAdicionarBairro = new javax.swing.JButton();
        btnRemoverBairro = new javax.swing.JButton();
        lblBairroCRUD = new javax.swing.JLabel();
        lblTaxa = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtTaxa = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        lblBairros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBairros.setText("Bairro:");

        btnAdicionarBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarBairro.setText("Adicionar");
        btnAdicionarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarBairroActionPerformed(evt);
            }
        });

        btnRemoverBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverBairro.setText("Remover");
        btnRemoverBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverBairroActionPerformed(evt);
            }
        });

        lblBairroCRUD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBairroCRUD.setText("Bairros Registrados:");

        lblTaxa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTaxa.setText("Taxa:");

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTaxa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jTable1.setModel(vTabela);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlBairroCRUDLayout = new javax.swing.GroupLayout(pnlBairroCRUD);
        pnlBairroCRUD.setLayout(pnlBairroCRUDLayout);
        pnlBairroCRUDLayout.setHorizontalGroup(
            pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                            .addComponent(btnAdicionarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(173, 173, 173)
                            .addComponent(btnRemoverBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(169, 169, 169)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairroCRUD)
                            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                                .addGap(458, 458, 458)
                                .addComponent(lblTaxa))
                            .addComponent(lblBairros, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBairroCRUDLayout.setVerticalGroup(
            pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBairroCRUD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairros)
                    .addComponent(lblTaxa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBairroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarBairro)
                    .addComponent(btnRemoverBairro)
                    .addComponent(btnAlterar))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBairroCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBairroCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            TlAlterarBairros alt = new TlAlterarBairros(this);

            alt.lbCod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
            alt.txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
            alt.txtTaxa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "");

            alt.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnRemoverBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverBairroActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            int Cod = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");

            PerBairros pa = new PerBairros();
            pa.DeletarBairros(Cod);

            PreencherTabela();
            txtBairro.setText("");
            txtTaxa.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela para remover!");
        }

    }//GEN-LAST:event_btnRemoverBairroActionPerformed

    private void btnAdicionarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarBairroActionPerformed

        if (txtBairro.getText().isEmpty() || txtTaxa.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Um dos campos está vazia, verifique novamente!");

        } else {
            ClsBairros addBairros = new ClsBairros();

            addBairros.setNome(txtBairro.getText());
            addBairros.setPreco(Double.parseDouble(txtTaxa.getText()));

            PerBairros.InserirBairros(addBairros);

            PreencherTabela();
            txtBairro.setText("");
            txtTaxa.setText("");
        }
    }//GEN-LAST:event_btnAdicionarBairroActionPerformed

    public void PreencherTabela() {
        //vai limpar a tabela
        int t = vTabela.getRowCount();
        for (int i = 0; i < t; i++) {
            vTabela.removeRow(0);
        }

        PerBairros perbairros = new PerBairros();
        ArrayList<ClsBairros> bairros = PerBairros.TodosBairros();

        //vai preencher a tabela
        for (ClsBairros q : bairros) {
            String linha[] = new String[3];

            linha[0] = q.getCod() + "";
            linha[1] = q.getNome();
            linha[2] = q.getPreco() + "";
            vTabela.addRow(linha);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarBairro;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRemoverBairro;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBairroCRUD;
    private javax.swing.JLabel lblBairros;
    private javax.swing.JLabel lblTaxa;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlBairroCRUD;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtTaxa;
    // End of variables declaration//GEN-END:variables
}
