package Fronteira;

import Controle.ClsComplemento;
import Persistencia.PerComplemento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TlComplemento extends javax.swing.JPanel {

    DefaultTableModel vTabela = new DefaultTableModel();

    public TlComplemento() {
        initComponents();
        vTabela.addColumn("Cod.");
        vTabela.addColumn("Nome do Complemento");
        vTabela.addColumn("Preço");
        PreencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlComplemento = new javax.swing.JPanel();
        lblComplementos = new javax.swing.JLabel();
        btnCompAdicionar = new javax.swing.JButton();
        btnCompRemover = new javax.swing.JButton();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblCompValor = new javax.swing.JLabel();
        txtCompValor = new javax.swing.JTextField();
        btnCompAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(800, 600));

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        lblComplementos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblComplementos.setText("Complementos:");

        btnCompAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCompAdicionar.setText("Adicionar");
        btnCompAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompAdicionarActionPerformed(evt);
            }
        });

        btnCompRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCompRemover.setText("Remover");
        btnCompRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompRemoverActionPerformed(evt);
            }
        });

        lblComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblComplemento.setText("Complemento:");

        txtComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblCompValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCompValor.setText("Valor:");

        txtCompValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCompAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCompAlterar.setText("Alterar");
        btnCompAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompAlterarActionPerformed(evt);
            }
        });

        jTable1.setModel(vTabela);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlComplementoLayout = new javax.swing.GroupLayout(pnlComplemento);
        pnlComplemento.setLayout(pnlComplementoLayout);
        pnlComplementoLayout.setHorizontalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComplementoLayout.createSequentialGroup()
                        .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlComplementoLayout.createSequentialGroup()
                                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComplemento)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCompValor, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCompValor)))
                            .addGroup(pnlComplementoLayout.createSequentialGroup()
                                .addComponent(btnCompAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(btnCompRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCompAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(pnlComplementoLayout.createSequentialGroup()
                        .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComplementos)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlComplementoLayout.setVerticalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComplementos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(lblCompValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompAdicionar)
                    .addComponent(btnCompRemover)
                    .addComponent(btnCompAlterar))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompRemoverActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            int Cod = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");

            PerComplemento pa = new PerComplemento();
            pa.DeletarComplemento(Cod);

            PreencherTabela();
            txtComplemento.setText("");
            txtCompValor.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela para remover!");
        }

    }//GEN-LAST:event_btnCompRemoverActionPerformed

    private void btnCompAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompAdicionarActionPerformed

        if (txtComplemento.getText().isEmpty() || txtCompValor.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Um dos campos está vazia, verifique novamente!");

        } else {

            ClsComplemento addComplemento = new ClsComplemento();

            addComplemento.setNome(txtComplemento.getText());
            addComplemento.setPreco(Double.parseDouble(txtCompValor.getText()));

            PerComplemento.InserirComplemento(addComplemento);

            PreencherTabela();
            txtComplemento.setText("");
            txtCompValor.setText("");
        }
    }//GEN-LAST:event_btnCompAdicionarActionPerformed

    private void btnCompAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompAlterarActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            TlAlterarComplemento alt = new TlAlterarComplemento(this);

            alt.lbCod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
            alt.txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
            alt.txtValor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "");

            alt.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }

    }//GEN-LAST:event_btnCompAlterarActionPerformed

    public void PreencherTabela() {
        //vai limpar a tabela
        int t = vTabela.getRowCount();
        for (int i = 0; i < t; i++) {
            vTabela.removeRow(0);
        }

        PerComplemento percomplemento = new PerComplemento();
        ArrayList<ClsComplemento> complemento = PerComplemento.TodosComplemento();

        //vai preencher a tabela
        for (ClsComplemento q : complemento) {
            String linha[] = new String[3];

            linha[0] = q.getCod() + "";
            linha[1] = q.getNome();
            linha[2] = q.getPreco() + "";
            vTabela.addRow(linha);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompAdicionar;
    private javax.swing.JButton btnCompAlterar;
    private javax.swing.JButton btnCompRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCompValor;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblComplementos;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlComplemento;
    private javax.swing.JTextField txtCompValor;
    private javax.swing.JTextField txtComplemento;
    // End of variables declaration//GEN-END:variables
}
