package Fronteira;

import Controle.ClsVitamina;
import Persistencia.PerVitamina;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TlVitamina extends javax.swing.JPanel {

    DefaultTableModel vTabela = new DefaultTableModel();

    public TlVitamina() {
        initComponents();
        vTabela.addColumn("Cod.");
        vTabela.addColumn("Tipo");
        vTabela.addColumn("Nome da Vitamina");
        vTabela.addColumn("Preço");
        PreencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlVitaminas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVitRemover = new javax.swing.JButton();
        btnVitAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtVitTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVitNome = new javax.swing.JTextField();
        btnVitAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        pnlBack.setBackground(new java.awt.Color(204, 204, 224));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Vitaminas:");

        btnVitRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitRemover.setText("Remover");
        btnVitRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitRemoverActionPerformed(evt);
            }
        });

        btnVitAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitAdicionar.setText("Adicionar");
        btnVitAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        txtVitTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor:");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        txtVitNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnVitAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVitAlterar.setText("Alterar");
        btnVitAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitAlterarActionPerformed(evt);
            }
        });

        jTable1.setModel(vTabela);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlVitaminasLayout = new javax.swing.GroupLayout(pnlVitaminas);
        pnlVitaminas.setLayout(pnlVitaminasLayout);
        pnlVitaminasLayout.setHorizontalGroup(
            pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVitaminasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlVitaminasLayout.createSequentialGroup()
                                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVitTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtVitNome, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlVitaminasLayout.createSequentialGroup()
                        .addComponent(btnVitAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(btnVitRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)
                        .addComponent(btnVitAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVitaminasLayout.setVerticalGroup(
            pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVitaminasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVitTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVitNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVitaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitAdicionar)
                    .addComponent(btnVitRemover)
                    .addComponent(btnVitAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVitaminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVitaminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitAdicionarActionPerformed

        if (txtVitTipo.getText().isEmpty() || txtVitNome.getText().isEmpty() || txtPreco.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Um dos campos está vazia, verifique novamente!");

        } else {

            ClsVitamina addVitamina = new ClsVitamina();

            addVitamina.setTipo(txtVitTipo.getText());
            addVitamina.setNome(txtVitNome.getText());
            addVitamina.setPreco(Double.parseDouble(txtPreco.getText()));

            PerVitamina.InserirVitamina(addVitamina);

            PreencherTabela();
            txtVitTipo.setText("");
            txtVitNome.setText("");
            txtPreco.setText("");
        }
    }//GEN-LAST:event_btnVitAdicionarActionPerformed

    private void btnVitRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitRemoverActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            int Cod = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");

            PerVitamina pa = new PerVitamina();
            pa.DeletarVitamina(Cod);

            PreencherTabela();
            txtVitTipo.setText("");
            txtVitNome.setText("");
            txtPreco.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela para remover!");
        }

    }//GEN-LAST:event_btnVitRemoverActionPerformed

    private void btnVitAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitAlterarActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            TlAlterarVitamina alt = new TlAlterarVitamina(this);

            alt.lbCod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
            alt.txtTipo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
            alt.txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "");
            alt.txtValor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3) + "");

            alt.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }

    }//GEN-LAST:event_btnVitAlterarActionPerformed

    public void PreencherTabela() {
        //vai limpar a tabela
        int t = vTabela.getRowCount();
        for (int i = 0; i < t; i++) {
            vTabela.removeRow(0);
        }

        PerVitamina pervitamina = new PerVitamina();
        ArrayList<ClsVitamina> vitamina = PerVitamina.TodasVitaminas();

        //vai preencher a tabela
        for (ClsVitamina q : vitamina) {
            String linha[] = new String[4];

            linha[0] = q.getCod() + "";
            linha[1] = q.getTipo();
            linha[2] = q.getNome();
            linha[3] = q.getPreco() + "";
            vTabela.addRow(linha);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVitAdicionar;
    private javax.swing.JButton btnVitAlterar;
    private javax.swing.JButton btnVitRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlVitaminas;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtVitNome;
    private javax.swing.JTextField txtVitTipo;
    // End of variables declaration//GEN-END:variables
}
